version: "3.8"
services:
  api-server:
    image: formio/submission-server
    mem_limit: 1024m
    volumes:
      - "./certs:/src/certs:ro"
    environment:
      PORT: 3000
      PROXY: "true"
      SSL_CERT: ${SSL_CERT}
      SSL_KEY: ${SSL_KEY}
      MONGO_CA: /src/certs/rds-combined-ca-bundle.pem
    env_file:
      - .env
  nginx-proxy:
    image: nginx
    mem_limit: 128m
    ports:
      - "443:443"
    volumes:
      - "./certs:/src/certs:ro"
      - "./conf.d.ssl:/etc/nginx/conf.d:ro"
    links:
      - api-server
