version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - "./data/db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
  minio:
    image: minio/minio
    restart: always
    volumes:
      - "./data/minio/data:/data"
      - "./data/minio/config:/root/.minio"
    environment:
      MINIO_ACCESS_KEY: CHANGEME
      MINIO_SECRET_KEY: CHANGEME
    command: server /data
  pdf-libs:
    image: formio/pdf-libs:1.0.0
    mem_limit: 256m
    environment:
      PORT: 8080
    env_file:
      - .env
  pdf-converter:
    image: 551091399009.dkr.ecr.us-east-1.amazonaws.com/pdf-converter:latest
    mem_limit: 1024m
    links:
      - pdf-libs
    environment:
      PDFLIBS_URL: http://pdf-libs:8080
      PORT: 4000
      SNS_LISTENER_PORT: 4444
    ports:
      - "4444:4444"
    env_file:
      - .env
  api-server:
    image: formio/formio-enterprise
    mem_limit: 1024m
    ports:
      - "3000:3000"
    links:
      - mongo
      - pdf-server
    volumes:
      - "./certs:/src/certs:ro"
    environment:
      MONGO: mongodb://mongo:27017/formio
      PDF_SERVER: http://pdf-server:4005
      PORTAL_ENABLED: 1
      PORT: 3000
    env_file:
      - .env
  pdf-server:
    image: formio/pdf-server
    mem_limit: 1024m
    links:
      - mongo
      - minio
      - pdf-libs
      - pdf-converter
    ports:
      - "4005:4005"
    volumes:
      - "./certs:/src/certs:ro"
    environment:
      MONGO: mongodb://mongo:27017/formio
      FORMIO_S3_SERVER: minio
      FORMIO_S3_PORT: 9000
      FORMIO_S3_BUCKET: formio
      FORMIO_S3_KEY: CHANGEME
      FORMIO_S3_SECRET: CHANGEME
      PDF2FORMIO_URL: http://pdf-converter:4000
      PDFLIBS_URL: http://pdf-libs:8080
      FORMIO_PDF_PORT: 4005
    env_file:
      - .env
  nginx-proxy:
    image: nginx
    mem_limit: 128m
    ports:
      - "80:80"
    volumes:
      - "./certs:/src/certs:ro"
      - "./conf.d:/etc/nginx/conf.d:ro"
    links:
      - api-server
      - pdf-server
